package com.zlstudy.entity;
// Generated 2016-10-9 10:17:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * TaskRep generated by hbm2java
 */
@Entity
@Table(name = "task_rep", catalog = "newsclient_hnxxt")
public class TaskRep implements java.io.Serializable {

	private Integer id;
	private Integer taskId;
	private Long userId;
	private String name;
	private String attachment;
	private Integer status;
	private Date createTime;
	private Date updateTime;
	
	private String title;
	private String requires;
	private String taskAttachment;

	public TaskRep() {
	}

	public TaskRep(Integer taskId, Long userId, String name, String attachment, Integer status, Date createTime,
			Date updateTime) {
		this.taskId = taskId;
		this.userId = userId;
		this.name = name;
		this.attachment = attachment;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "taskId")
	public Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(Integer taskId) {
		this.taskId = taskId;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "attachment", length = 512)
	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Transient
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Transient
	public String getRequires() {
		return requires;
	}

	public void setRequires(String requires) {
		this.requires = requires;
	}

	@Transient
	public String getTaskAttachment() {
		return taskAttachment;
	}

	public void setTaskAttachment(String taskAttachment) {
		this.taskAttachment = taskAttachment;
	}

}
