package com.zlstudy.entity;
// Generated 2016-10-9 10:17:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TaskPub generated by hbm2java
 */
@Entity
@Table(name = "task_pub", catalog = "newsclient_hnxxt")
public class TaskPub implements java.io.Serializable {

	private Integer id;
	private Integer chapterNo;
	private Integer sectionNo;
	private String title;
	private Integer type;
	private Integer needReply;
	private String requires;
	private String attachment;
	private Long userId;
	private Integer ranges;
	private Integer loadNum;
	private Integer replyNum;
	private Integer status;
	private Date createTime;
	private Date updateTime;

	public TaskPub() {
	}

	public TaskPub(Integer chapterNo, Integer sectionNo, String title, Integer type, Integer needReply, String requires,
			String attachment, Long userId, Integer ranges, Integer loadNum, Integer replyNum, Integer status,
			Date createTime, Date updateTime) {
		this.chapterNo = chapterNo;
		this.sectionNo = sectionNo;
		this.title = title;
		this.type = type;
		this.needReply = needReply;
		this.requires = requires;
		this.attachment = attachment;
		this.userId = userId;
		this.ranges = ranges;
		this.loadNum = loadNum;
		this.replyNum = replyNum;
		this.status = status;
		this.createTime = createTime;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "chapterNo")
	public Integer getChapterNo() {
		return this.chapterNo;
	}

	public void setChapterNo(Integer chapterNo) {
		this.chapterNo = chapterNo;
	}

	@Column(name = "sectionNo")
	public Integer getSectionNo() {
		return this.sectionNo;
	}

	public void setSectionNo(Integer sectionNo) {
		this.sectionNo = sectionNo;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "needReply")
	public Integer getNeedReply() {
		return this.needReply;
	}

	public void setNeedReply(Integer needReply) {
		this.needReply = needReply;
	}

	@Column(name = "requires")
	public String getRequires() {
		return this.requires;
	}

	public void setRequires(String requires) {
		this.requires = requires;
	}

	@Column(name = "attachment", length = 512)
	public String getAttachment() {
		return this.attachment;
	}

	public void setAttachment(String attachment) {
		this.attachment = attachment;
	}

	@Column(name = "userId")
	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	@Column(name = "ranges")
	public Integer getRanges() {
		return this.ranges;
	}

	public void setRanges(Integer ranges) {
		this.ranges = ranges;
	}

	@Column(name = "loadNum")
	public Integer getLoadNum() {
		return this.loadNum;
	}

	public void setLoadNum(Integer loadNum) {
		this.loadNum = loadNum;
	}

	@Column(name = "replyNum")
	public Integer getReplyNum() {
		return this.replyNum;
	}

	public void setReplyNum(Integer replyNum) {
		this.replyNum = replyNum;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "createTime", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
